export const THEMES = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
  "dim",
  "nord",
  "sunset",
];

export const CONTACTS = [
  {
    id: 1,
    name: "Jane Doe",
    status: "Offline",
    avatar:
      "https://res.cloudinary.com/nexuschatapp/image/upload/v1735374621/hpcgxxezqwzssgeaerxg.jpg",
  },
  {
    id: 2,
    name: "Emma Thompson",
    status: "Offline",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: 3,
    name: "Sophia Davis",
    status: "Offline",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 4,
    name: "Charlotte Williams",
    status: "Offline",
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: 5,
    name: "Amelia Garcia",
    status: "Offline",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 6,
    name: "James Anderson",
    status: "Offline",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 7,
    name: "William Clark",
    status: "Offline",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
  },
];

export const CHAT_MESSAGES = [
  { id: 1, content: "Thanks for the help! 👍", time: "14:30", isSent: false },
  { id: 2, content: "No problem at all", time: "14:32", isSent: true },
  { id: 3, content: "Meeting at 3pm?", time: "14:35", isSent: false },
  { id: 4, content: "Perfect, see you then", time: "14:36", isSent: true },
  { id: 5, content: "Great! 🎉", time: "14:37", isSent: false },
];
